export default {
  types: {
    AuctionId: 'u32',
    AuctionIdOf: 'AuctionId',
    CurrencyIdOf: 'CurrencyId',
    Amount: 'i128',
    AmountOf: 'Amount',
    DebitAmount: 'Amount',
    DebitAmountOf: 'DebitAmount',
    DebitBalance: 'Balance',
    DebitBalanceOf: 'Balance',
    OracleKey: 'CurrencyId',
    OracleValue: 'Price',
    Share: 'u128',
    DestAddress: '[u8; 20]',
    AsOriginId: {
      _enum: ['Root', 'AcalaTreasury', 'HonzonTreasury', 'HomaTreasury', 'DSWF']
    },
    // @TODO https://github.com/polkadot-js/api/pull/2692/files#r502010063
    // PalletsOrigin: {
    //   _enum: {
    //     System: 'SystemOrigin',
    //     Timestamp: 'Null',
    //     RandomnessCollectiveFlip: 'Null',
    //     Balances: 'Null',
    //     Accounts: 'Null',
    //     Currencies: 'Null',
    //     Tokens: 'Null',
    //     Vesting: 'Null',
    //     AcalaTreasury: 'Null',
    //     Utility: 'Null',
    //     Multisig: 'Null',
    //     Recovery: 'Null',
    //     Proxy: 'Null',
    //     Scheduler: 'Null',
    //     Indices: 'Null',
    //     GraduallyUpdate: 'Null',
    //     Authorship: 'Null',
    //     Babe: 'Null',
    //     Grandpa: 'Null',
    //     Staking: 'Null',
    //     Session: 'Null',
    //     Historical: 'Null',
    //     GeneralCouncil: 'CollectiveOrigin',
    //     GeneralCouncilMembership: 'Null',
    //     HonzonCouncil: 'CollectiveOrigin',
    //     HonzonCouncilMembership: 'Null',
    //     HomaCouncil: 'CollectiveOrigin',
    //     HomaCouncilMembership: 'Null',
    //     TechnicalCommittee: 'CollectiveOrigin',
    //     TechnicalCommitteeMembership: 'Null',
    //     Authority: 'DelayedOrigin',
    //     ElectionsPhragmen: 'Null',
    //     AcalaOracle: 'Null',
    //     BandOracle: 'Null',
    //     OperatorMembershipAcala: 'Null',
    //     OperatorMembershipBand: 'Null',
    //     Auction: 'Null',
    //     Rewards: 'Null',
    //     OrmlNFT: 'Null',
    //     Prices: 'Null',
    //     Dex: 'Null',
    //     AuctionManager: 'Null',
    //     Loans: 'Null',
    //     Honzon: 'Null',
    //     CdpTreasury: 'Null',
    //     CdpEngine: 'Null',
    //     EmergencyShutdown: 'Null',
    //     Homa: 'Null',
    //     NomineesElection: 'Null',
    //     StakingPool: 'Null',
    //     PolkadotBridge: 'Null',
    //     Incentives: 'Null',
    //     AirDrop: 'Null',
    //     NFT: 'Null',
    //     RenVmBridge: 'Null',
    //     Contracts: 'Null',
    //     EVM: 'Null',
    //     Sudo: 'Null',
    //     TransactionPayment: 'Null'
    //   }
    // }
  }
};
