/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Erc20 } from "./Erc20.js";
export * as factories from "./factories/index.js";
export { Erc20__factory } from "./factories/Erc20__factory.js";
